apiVersion: v1
kind: Pod
metadata:
  name: myfapi
  labels:
    app: myfapi
spec:
  containers:
  - name: api
    image: kramerscs/myfapi:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
